openapi: 3.0.0
info:
  title: Finance Calculator API
  description: API for calculating future value, present value, payment amount, and interest rate per year for financial purposes.
  version: 1.0.0
servers:
  - url: https://a8cf-184-185-222-8.ngrok-free.app/api
    description: Main API server
paths:
  /calculate_fv:
    post:
      operationId: calculateFutureValue
      summary: Calculate future value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [PV, IY, N, PMT, Settings]
              properties:
                PV:
                  type: number
                  description: Present Value
                IY:
                  type: number
                  description: Interest Rate Per Year
                N:
                  type: integer
                  description: Number of Periods
                PMT:
                  type: number
                  description: Payment Amount
                Settings:
                  type: object
                  properties:
                    CY:
                      type: integer
                      description: Compounding periods per year
                      default: 1
                    PMTAtStart:
                      type: boolean
                      description: Payment at the beginning of the period
                      default: false
      responses:
        '200':
          description: Successful calculation of future value
          content:
            application/json:
              schema:
                type: object
                properties:
                  FV:
                    type: number
                    description: Future Value

  /calculate_pv:
    post:
      operationId: calculatePresentValue
      summary: Calculate present value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [FV, IY, N, PMT, Settings]
              properties:
                FV:
                  type: number
                  description: Future Value
                IY:
                  type: number
                  description: Interest Rate Per Year
                N:
                  type: integer
                  description: Number of Periods
                PMT:
                  type: number
                  description: Payment Amount
                Settings:
                  type: object
                  properties:
                    CY:
                      type: integer
                      description: Compounding periods per year
                      default: 1
                    PMTAtStart:
                      type: boolean
                      description: Payment at the beginning of the period
                      default: false
      responses:
        '200':
          description: Successful calculation of present value
          content:
            application/json:
              schema:
                type: object
                properties:
                  PV:
                    type: number
                    description: Present Value

  /calculate_pmt:
    post:
      operationId: calculatePayment
      summary: Calculate payment amount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [FV, IY, N, PV, Settings]
              properties:
                FV:
                  type: number
                  description: Future Value
                IY:
                  type: number
                  description: Interest Rate Per Year
                N:
                  type: integer
                  description: Number of Periods
                PV:
                  type: number
                  description: Present Value
                Settings:
                  type: object
                  properties:
                    CY:
                      type: integer
                      description: Compounding periods per year
                      default: 1
                    PMTAtStart:
                      type: boolean
                      description: Payment at the beginning of the period
                      default: false
      responses:
        '200':
          description: Successful calculation of payment amount
          content:
            application/json:
              schema:
                type: object
                properties:
                  PMT:
                    type: number
                    description: Payment Amount

  /calculate_iy:
    post:
      operationId: calculateInterestRate
      summary: Calculate interest rate per year
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [PV, FV, N, PMT, Settings]
              properties:
                PV:
                  type: number
                  description: Present Value
                FV:
                  type: number
                  description: Future Value
                N:
                  type: integer
                  description: Number of Periods
                PMT:
                  type: number
                  description: Payment Amount
                Settings:
                  type: object
                  properties:
                    CY:
                      type: integer
                      description: Compounding periods per year
                      default: 1
                    PMTAtStart:
                      type: boolean
                      description: Payment at the beginning of the period
                      default: false
      responses:
        '200':
          description: Successful calculation of interest rate per year
          content:
            application/json:
              schema:
                type: object
                properties:
                  IY:
                    type: number
                    description: Interest Rate Per Year
